name: Checks
on:
  push:
    branches:
      - main
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Bun
        uses: oven-sh/setup-bun@v1.2.0
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Check formatting
        run: bun format:check
      - name: Lint
        run: bun lint
      - name: Check types
        run: bun type:check
